apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ds-resource-injector
  name: ds-resource-injector
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ds-resource-injector
  template:
    metadata:
      labels:
        app: ds-resource-injector
    spec:
      tolerations:
        - key: acme.com/lifespan-remaining
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        karpenter.sh/provisioner-name: stk
      serviceAccountName: ds-resource-injector
      containers:
        - image: 441218111557.dkr.ecr.us-west-2.amazonaws.com/baseimage-ci:ds-resource-injector
          imagePullPolicy: Always
          name: ds-resource-injector
          env:
            - name: TLS
              value: "true"
            - name: LOG_LEVEL
              value: "debug"
            - name: LOG_JSON
              value: "false"
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
              readOnly: true
      volumes:
        - name: tls
          secret:
            secretName: ds-resource-injector-tls
